"use server"

import { prisma } from "@/lib/prisma";
import { supabase } from "@/lib/supabaseClient";

export async function getAuthenticatedUser() {
  try {
    // 1. Get the current user session from Supabase Auth
    const { data: { user }, error } = await supabase.auth.getUser();

    // If there is no user or an auth error, return null safely
    if (error || !user) {
      return null;
    }

    // 2. Use the Supabase UID to find the matching record in Prisma
    // We use lowercase 'credentials' as generated by the Prisma Client
    const dbUser = await prisma.credentials.findUnique({
      where: { 
        user_id: user.id 
      },
    });

    return dbUser;
  } catch (err) {
    // Log the error for debugging, but return null so the UI can handle the 'logged out' state
    console.error("Critical error fetching authenticated user:", err);
    return null;
  }
}